### ISSUE TITLE
DTW between open_TWTR and open_FB seems largest??

### ISSUE THREAD

**Issue by TomLin** [ddaskan/trendypy#1]
Hello Dogan, 

It's so great that you wrote such a completed introduction for trend/time series clustering.
However, when I was trying to re-run the script in your github repo. I found out there is some weird figures on DTW distance.

As my DTW result between open_TWTR and open_FB is largest, but that should be the smallest, right? You can see the result image below. It would be great if you could help on my question. Thanks a lot.
(although I don't understand the logics behind DTW, but I assume the smaller value on DTW means the two series are the most similar)

![image](https://user-images.githubusercontent.com/15340452/53639118-4e9f4380-3c63-11e9-96b6-27c63111aa19.png)

**Comment by ddaskan** [comment]
Hi Tom,

Yes, smaller value means closer in terms of distance. But, remember I've created that notebook 5 months ago with that day's actual. So, trends may have changed. Here are my suggestions;

1. Try to limit stock data according to notebook. Start Date is already in notebook, End Date should be September 27, 2018. Be sure to also check argument `scale`.
2. Try to visualize trends both as scaled and not scaled, you should also be able to identify which is closer to which during debugging. So you can justify values.

Let me know how this goes, I can dig deeper if necessary.

**Comment by TomLin** [comment]
Yes!! It's successfully solved. It turns out that I need to specify the ending date (2018-09-27) for the dataset. 

By the way, I found out that the old script for this line doesn't output the expected series, probably because of the version issue:
https://github.com/ddaskan/Time_Series_Clustering/blob/c4024549506749da9eb8ab62eea347ac12ad6642/trendy.py#L85

![image](https://user-images.githubusercontent.com/15340452/53678653-409e0100-3cfd-11e9-9047-bbbaf8790b2a.png)

I instead wrap up the series in a list `series_keys = pd.Series(list(series.keys()))`, just for your reference and others running the script.

Thanks again for your wonderful work.

**Comment by ddaskan** [comment]
Perfect! Glad that we can close the issue.

Yes, I should have added a requirement file, my bad. I'll do soon.
