### ISSUE TITLE
For the large memory cost.

### ISSUE THREAD

**Issue by domilay** [ddaskan/trendypy#6]
Hey, I am currently using the function Trendy for processing 300 sequences to 10 clusters, the length of each sequence is 24. The problem I face is when processing, the memory cost is just increasing to 80G even I compute on a server, and return the memoryerror message. Is this normal? Thanks a lot.

**Comment by ddaskan** [comment]
Hi, it's expected that it uses a lot of memory, not sure about the particular figures you mentioned though. Let me explain why.

Trendy is great when you have **small amount of data of sequences with different (i.e. non-fixed) lengths**. However, unlike the other clustering methods (e.g. k-means), Trendy does **not** generalize on the data. It does **not** converge. This means it exactly evaluates every single n-combination (i.e. n=10 in your case) for the set S (i.e. S=300) to find the best cluster combination. As you can image, this number is a very big number, specifically `300!/10!*(300-10)!`, see [combination](https://en.wikipedia.org/wiki/Combination). This is also the space complexity of the algorithm. I know it's not much memory friendly 😄 .

You may do two things to mitigate this;

1. **You may try to lower that number.** Like I explained, unlike the conventional methods, it's hard to say more data improve the success of the model. Instead, extra similar data points (i.e. sequences) unnecessarily and significantly increase the computation time. For example, if you know 10 of those sequences are very similar, you can just remove 9 of them. The result won't be much different. Or, you may try to cluster by batches if you have some prior information of the potential first level grouping (maybe 200 of them coming from 2 distinct data points, so the first batch S=200, n=2 and the second batch S=100, n=8).
2. **You may try a different method.** In your specific example, I see that you have fixed length of sequences (i.e. 24). So, you may just want to try 10-means clustering on the data with 24 dimension.

Anyway, I'll definitely keep this in mind and try to find a way to handle this. This won't be quick though.

**Comment by domilay** [comment]
Thank you very much for your detailed answer, you are so kind. I have understood it. You are so kind.

**Comment by ddaskan** [comment]
You're welcome.
